// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package api

import (
	"github.com/google/wire"
	"go-portfolio/server/api/contract"
	"go-portfolio/server/api/handler"
	"go-portfolio/server/api/repository"
	"go-portfolio/server/api/service"
	"go-portfolio/server/lib/database"
	"go-portfolio/server/lib/environment"
	"go-portfolio/server/lib/logger"
)

// Injectors from wire.go:

// 3. Injector
func InitializeAPI(cfg *environment.Config, log *logger.Logger) (*handler.Handler, error) {
	db, err := database.ProvideSQLDatabase(cfg)
	if err != nil {
		return nil, err
	}
	projectRepository := repository.NewProjectRepository(db)
	projectService := service.NewProjectService(projectRepository, log)
	experienceRepository := repository.NewExperienceRepository(db)
	experienceService := service.NewExperienceService(experienceRepository, log)
	handlerHandler := handler.NewHandler(projectService, experienceService, log)
	return handlerHandler, nil
}

// wire.go:

// Grouping services
var ProjectSet = wire.NewSet(repository.NewProjectRepository, wire.Bind(new(contract.IProjectRepository), new(*repository.ProjectRepository)), service.NewProjectService, wire.Bind(new(contract.IProjectService), new(*service.ProjectService)))

// 2.experience services
var ExperienceSet = wire.NewSet(repository.NewExperienceRepository, wire.Bind(new(contract.IExperienceRepository), new(*repository.ExperienceRepository)), service.NewExperienceService, wire.Bind(new(contract.IExperienceService), new(*service.ExperienceService)))
