run:
  timeout: 5m

issues:
  exclude-dirs:
    - docs
  exclude-files:
    - ".*_gen\\.go$"

  exclude-rules:
    - path: _gen\.go
      linters:
        - typecheck
        - staticcheck
        - unused
